danielberkompas/ex_twilio

.travis.yml, lib/ex_twilio/resource.ex, lib/ex_twilio/url_generator.ex, mix.exs
Elixir has built-in language features which do some tasks more elegantly
than the Enum module. This PR refactors the code in favor of those.
=> Reduce reliance on Enum

mix.exs, mix.lock
Prior to this commit, the Poison dependency was pinned to anything in
the 1.4.x series; however, given that Poison follows semantic
versioning, we should pin to 1.x (where x >= 4) instead. This will allow
compatibility for dependency resolution when bundled with other projects
that may require a newer version of Poison, such as Phoenix.
=>  pin Poison dependency to >= 1.4 and < 2

mix.exs, mix.lock
Version `4.1.1` of [ibrowse](https://github.com/cmullaparthi/ibrowse) doesn't work with OTP 18, since the OS function `now()` is deprecated. This brings the dependency up a single patch level to solve the issue.
More info: https://github.com/cmullaparthi/ibrowse/issues/129
=> Upgrade ibrowse dependency for R18 support

mix.exs
All the runtime dependencies should be listed in the `applications` part - no matter if they have their own supervisors or not. Only the applications from that list are included in the releases.
=> Add missing applications to app template

lib/ex_twilio/url_generator.ex, lib/ex_twilio/utils.ex, test/ex_twilio/utils_test.exs
As mentioned in #19, Mix.Utils should not be used for camelization and
underscoring, because this requires users to include mix in the
application configuration.
This commit copies the relevant parts of Mix.Utils into an
"ExTwilio.Utils" module. This avoids adding another dependency for such
a small thing.
Fixes #19.
=> [#19]: Stop using Mix.Utils

README.md
These functions were deleted during some refactoring a while ago. They
should no longer be displayed in the README.
Closes #23.
=> Remove deleted functions from README

lib/ex_twilio/url_generator.ex, test/ex_twilio/url_generator_test.exs
Twilio requires that multiple StatusCallbackEvent params be passed as separate params; the current version of to_query_string strips multiple value for params by mapping them into a Map, which does not allow multiple values for a key.
As a sidenote, some of the doctests do not pass.
=> Allow query strings to contain multiple values for a param

lib/ex_twilio/parser.ex, test/ex_twilio/parser_test.exs
Upgrading to Poison 2.0 broke the parser. This fixes it.
=> Fix Parser for Poison 2.0

lib/ex_twilio/result_stream.ex
The previous variable next_page_uri was returning the end point `/2010-04-01/Accounts/xxxxxxx/Messages.json` and causing HTTPotion to raise a HTTPotion.HTTPError because it wasn't a full url.
There are four tests failing but this is because the doc test for the url_generator don't have an account_sid and are production an empty path: ie. https://api.twilio.com/2010-04-01/Accounts//Resources.json, but expect "https://api.twilio.com/2010-04-01/Accounts/Resources.json"
I'm not sure how to test this because it only shows up contacting Twilio and you have more that 50 resources to stream.
Fixes #38
=> Provide full url to process_page when there is more than 50 entries.

mix.exs, mix.lock
As it stands, ex_twilio cannot compile, because httppotion fails with "** (ArgumentError) Access is not a protocol"
=> This makes ex_twilio compatible with elixir 1.3

README.md
System variables are embedded in the compiled builds. By leaving the environment blank you can instead rely on EXRM to replace the variables:
References:
http://engineering.avvo.com/articles/using-env-with-elixir-and-docker.html
http://blog.plataformatec.com.br/2016/05/how-to-config-environment-variables-with-elixir-and-exrm/
=> Make the recommended config exrm compatible

README.md, lib/ex_twilio/api.ex, lib/ex_twilio/resources/lookup.ex
Merges [ex_twilio_lookup](https://github.com/HiOperator/ex_twilio_lookup) into ex_twilio. Thanks for the help @danielberkompas
=> Add lookup rest api

CALLING_TUTORIAL.md, lib/ex_twilio/capability.ex, test/ex_twilio/capability_test.exs
Hi @danielberkompas - I've implemented the instructions for receiving a call with Twilio that I'd previously left as `Pending...` in [CALLING_TUTORIAL.md](https://github.com/danielberkompas/ex_twilio/blob/master/CALLING_TUTORIAL.md).
Also, I did some minor refactoring to the `Capability` module as suggested by @pdawczak
=> Add instructions for receiving a call in the calling tutorial

lib/ex_twilio/capability.ex, test/ex_twilio/capability_test.exs
Right now outgoing capability token support is a bit useless, as you can't pass arbitary parameters along. This PR fixes this by allowing to pass params along with app id.
All the old bahaviour is saved, though few new cases have been added.
I've tested it with my app and it works (token got generated and after triggering call from the device, callback URL got the params).
=> Add specifying outgoing client capability params

lib/ex_twilio/resources/lookup.ex
I noticed the `caller_name` is missing for the lookup API, hence this PR :)
```
iex(1)> ExTwilio.Lookup.retrieve("+1234567890", Type: "caller-name")
{:ok,
%ExTwilio.Lookup.PhoneNumber{add_ons: nil,
caller_name: %{"caller_name" => "LIN HE", "caller_type" => "CONSUMER",
"error_code" => nil}, carrier: nil, country_code: "US", ...
```
=> Add caller_name field to lookup

.env.sample, .travis.yml, README.md, config/dev.exs, config/test.exs, lib/ex_twilio/config.ex, lib/ex_twilio/resource.ex, lib/ex_twilio/resources/task_router/activity.ex, lib/ex_twilio/resources/task_router/event.ex, lib/ex_twilio/resources/task_router/reservation.ex, lib/ex_twilio/resources/task_router/task.ex, lib/ex_twilio/resources/task_router/task_queue.ex, lib/ex_twilio/resources/task_router/task_queue_statistic.ex, lib/ex_twilio/resources/task_router/worker.ex, lib/ex_twilio/resources/task_router/worker_statistic.ex, lib/ex_twilio/resources/task_router/workflow.ex, lib/ex_twilio/resources/task_router/workflow_statistic.ex, lib/ex_twilio/resources/task_router/workspace.ex, lib/ex_twilio/resources/task_router/workspace_statistic.ex, lib/ex_twilio/url_generator.ex, lib/ex_twilio/worker_capability.ex, test/ex_twilio/worker_capability_test.exs
This is most likely going to take me a few days to implement.
- Resources
Let me know if there's anything you think I am missing @danielberkompas.
=> Implement Task Router API

lib/ex_twilio/url_generator.ex, test/ex_twilio/url_generator_test.exs
**The situation**
I would like to be notified by Twilio as an in-flight call I created progresses through various states. Using the current ExTwilio API, I would write:
```elixir
ExTwilio.Call.create(%{
to: ..., 
from: ..., 
application_sid: ..., 
status_callback_event: ["ringing", "answered", "completed"]
})
```
**The problem**
The creation attempt above throws an error:
```elixir
(ArgumentError) encode_query/1 values cannot be lists
```
**The culprit**
`ExTwilio.UrlGenerator.to_query_string` wraps a call to `URI.encode_query` which [forbids lists](https://hexdocs.pm/elixir/URI.html#encode_query/1) from being elements of the enumerable that we pass in.
The reasons why `URI.encode_query` forbids lists is essentially due to the lack of standards around encoding nested parameters in a URL. …
=> Handle query string encoding of list values for the param map.

.gitignore, lib/ex_twilio/url_generator.ex
Ran across this while working on another PR.  Looks like when TaskRouter was added this was left in rather than using the new config method.
I also added ```.DS_Store``` to the ```.gitignore``` to make things easier for osx-based contributors in the future.
=> Remove someone's hardcoded workspace sid from the url_builder

README.md, lib/ex_twilio/api.ex, lib/ex_twilio/config.ex, lib/ex_twilio/parent.ex, lib/ex_twilio/resource.ex, lib/ex_twilio/resources/member.ex, lib/ex_twilio/resources/programmable_chat/channel.ex, lib/ex_twilio/resources/programmable_chat/credential.ex, lib/ex_twilio/resources/programmable_chat/member.ex, lib/ex_twilio/resources/programmable_chat/message.ex, lib/ex_twilio/resources/programmable_chat/role.ex, lib/ex_twilio/resources/programmable_chat/service.ex, lib/ex_twilio/resources/programmable_chat/user.ex, lib/ex_twilio/resources/programmable_chat/user_channel.ex, lib/ex_twilio/resources/task_router/activity.ex, lib/ex_twilio/resources/task_router/event.ex, lib/ex_twilio/resources/task_router/reservation.ex, lib/ex_twilio/resources/task_router/task.ex, lib/ex_twilio/resources/task_router/task_queue.ex, lib/ex_twilio/resources/task_router/task_queue_statistic.ex, lib/ex_twilio/resources/task_router/worker.ex, lib/ex_twilio/resources/task_router/worker_statistic.ex, lib/ex_twilio/resources/task_router/workflow.ex, lib/ex_twilio/resources/task_router/workflow_statistic.ex, lib/ex_twilio/resources/task_router/workspace_statistic.ex, lib/ex_twilio/url_generator.ex, test/ex_twilio/url_generator_test.exs
- Added the [Programmable Chat API](https://www.twilio.com/docs/api/chat/rest)
- Minor additions and corrections to existing documentation
I ran into an issue where `infer_module/1` couldn't be trusted to choose the correct module as submodules under `ExTwilio` are added.  I played with a few options before settling on the strategy of defining a `ExTwilio.Parent` struct and supplying parents in that format for any resources under a submodule.  This makes sure that we are always guaranteed to use the correct module to determine the resource name at the expense of some slightly less pretty but more explicit parent definitions.  The `UrlGenerator` deals with all parents consistently regardless of how they were specified so the original resources can maintain their format.
Please let me know …
=> Add all endpoints for the programmable chat api.

README.md
Previous version of example does not work.
Resulted in:
{:error, "The requested resource /2010-04-01/Messages.json was not found", 404}
=> Config does not need system

lib/ex_twilio/url_generator.ex
After integrating ex_twilio into our app we noticed a bunch of console
output during test runs, it was because of this line.
=> Remove puts that could not be muted

lib/ex_twilio/result_stream.ex
I've read your article about streams in elixir and I think there's way to make ResultStream even less complicated.
@danielberkompas What do you think?
=> Refactor ExTwilio.ResultStream to simplify streaming code

lib/ex_twilio/request_validator.ex, lib/ex_twilio/result_stream.ex, test/ex_twilio/request_validator_test.exs
The URL builder initially has full url and when called with next_page_url(), it was generating something like this: `https://api.twilio.comhttps://api.twilio.com/....`
I think it makes sense to use `next_page_url/1` with `meta["next_page_uri"]`
If merged, this closes #88 
Also ran mix format on failing files on travis ci
=> fix next_page_url generation & run mix format

lib/ex_twilio/resources/message.ex
Updates the `ExTwilio.Message` struct with the `messaging_service_sid` field to allow retrieving this from the API response.
I was looking for somewhere to update/add a test for this change, however I couldn't see anywhere that this module is currently being tested directly. If I am missing something can you point me in the right direction please.
=> add messaging_service_sid to the message resource

lib/ex_twilio/resources/participant.ex
Currently the Participant resource does not include :create as an option. This PR proposes to add it.
Documentation from Twilio noting creation of a conference participant can be found by scrolling down to the second HTTP POST section here:
https://www.twilio.com/docs/voice/api/conference-participant#http-post
Example usage:
```
ExTwilio.Participant.create(%{"From" => "+15555555555", "To" => "+15555555556"}, account: "HelloWorldAccount", conference: "12345")
```
Addresses issue #102
=> Adds create to participant.

lib/ex_twilio/parser.ex, test/ex_twilio/parser_test.exs
`ExTwilio.Parser.parse` to handle 202 http status.
Resolves https://github.com/danielberkompas/ex_twilio/issues/97.
=> Parser to handle 202 http status

lib/ex_twilio/api.ex, lib/ex_twilio/parser.ex, test/ex_twilio/api_test.exs, test/ex_twilio/parser_test.exs
It would be useful to return the full error JSON for failed requests since that payload includes the error code, which is typically an easier and more reliable value to work with programmatically than the human-readable error message.
=> Parser: Return full error JSON

lib/ex_twilio/config.ex
Been getting Bypass to work with ExTwilio. While doing so, ExTwilio was sending requests to `https://localhost:port` when it should just be sending it to `http://localhost:port`. This adds a protocol option so that individuals can specify either `"https"` or `"http"` depending on their environment.
fixes #109
=> add protocol option for testing

lib/ex_twilio/resources/member.ex
=> fixing wrong resource_collection_name in ExTwilio.Memeber resource

lib/ex_twilio/resources/incoming_phone_number.ex
IncomingPhoneNumbers have been updated to have two new fields
1. `identity_sid`: a required sid (similar to address_sid) for purchasing phone numbers in certain foreign countries (eg Australia)
2. `status` a fully undocumented field. returns "in-use" if you attempt to CREATE a phone number your account already owns. (the API will return a 201 and behave as though you ran an UPDATE, but status will be "in-use" if you already own the number)
Our company opened a ticket re: `status` / multiple CREATE requests always succeeding. Twilio considers the behavior a feature, and did not comment on the undocumented nature of it.
=> Add status, identity_sid to IncomingPhoneNumber fields

lib/ex_twilio/config.ex, lib/ex_twilio/resources/fax.ex, lib/ex_twilio/url_generator.ex
Mostly straightforward, adding the faxing endpoint to `ex_twilio` according to their API docs here: https://www.twilio.com/docs/fax/quickstart
=> Add Fax resource

mix.exs, mix.lock
(Has a lot of fixes for pluralize.)
Tried to include ex_twilio in my project and it was conflicting due to older version of Inflex.  I was going to downgrade, but realized there are quite a few improvements in 2.0 for pluralize as well as the new `parameterize_to_ascii` which I am using in my project.
I experienced no breaks in my app and the ex_twilio test suite is still passing locally.
=> Bump Inflex to 2.0

README.md, lib/ex_twilio/jwt/access_token/voice_grant.ex, test/ex_twilio/jwt/access_token/voice_grant_test.exs, test/ex_twilio/jwt/access_token_test.exs
Voice grant enables to use Access Token in Voice SDKs.
Implementation is based on [Java version][1].
[1]: https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/jwt/accesstoken/VoiceGrant.java#L87
=> Add voice grant

lib/ex_twilio/api.ex, lib/ex_twilio/config.ex, test/ex_twilio/api_test.exs
Enables Twilio requests, for instance, to use a specific (non-default) hackney connection pool giving finer control over the maximum number of concurrent requests allowed on a specific node.
This would be done with the configuration
```elixir
config :ex_twilio, :request_options, hackney: [pool: :twilio_pool]
```
=> Allow request options to be configured for HTTPoison/hackney Twilio requests

lib/ex_twilio/request_validator.ex
Related to PR https://github.com/danielberkompas/ex_twilio/pull/147#issue-581644554 to support OTP 24
- fixes deprecation for `:cryto.hmac/3` with backward compatibility prior to OTP 22
- fixes deprecation warning for Bitwise.^^^ usage
=> fix(deprecation): :crypto.hmac -> :crypto.mac, Bitwise.^^^ -> Bitwise.bxor

README.md
When using elixir 1.3 or higher you will receive the following error when adding `ex_twilio` as application dependency.
```
** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```
I just modified the README
=> Documentation Clarification

bin/test, lib/ex_twilio/api.ex, lib/ex_twilio/jwt/access_token.ex, lib/ex_twilio/url_generator.ex
I'm now using this lib as a dependency on a private project and our dialyzer checks complained that a call to `ExTwilio.JWT.AccessToken.to_jwt!/1` would make the enclosing function have no local return. After some digging I've found the culprit - the success typing for `Joken.generate_and_sign!/3` requires that the second params is a map instead of `nil`.
That's one of the changes - I've also taken the opportunity to fix the remaining dialyzer errors on the project and added a new step to the Semaphore CI checks so we can ensure no more issues arise.
=> Fix dialyzer errors
